# Generated by Django 5.0.4 on 2024-09-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='my_related_obj',
            new_name='course',
        ),
    ]
