# Generated by Django 5.0.4 on 2024-09-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_options_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
