# Generated by Django 5.0.4 on 2024-09-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_public_id_alter_lesson_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('soon', 'Cooming soon'), ('draft', 'Draft')], default='draft', max_length=14),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('soon', 'Cooming soon'), ('draft', 'Draft')], default='draft', max_length=14),
        ),
    ]
