# Generated by Django 5.0.4 on 2024-09-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_status_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('soon', 'Coming soon'), ('draft', 'Draft')], default='draft', max_length=14),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('soon', 'Coming soon'), ('draft', 'Draft')], default='draft', max_length=14),
        ),
    ]
