# Generated by Django 5.0.4 on 2024-10-17 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
